### ISSUE TITLE
Podiamos centralizar vagas em um só lugar!

### ISSUE THREAD

**Issue by zeucxb** [FlutterComunidadeBR/vagas#3]
Já existe um repositório de vagas de flutter, seguindo um padrão bem legal. Pq não centralizar lá?

https://github.com/Flutter-Brazil/vagas

**Comment by JHBitencourt** [comment]
Foram criadas praticamente ao mesmo tempo, esse com 1 dia antes aparentemente haha.

De qualquer forma esse rep irá passar por reformulações.
